### ISSUE TITLE
Mono build was broken

### ISSUE THREAD

**Issue by NFlameInvasion** [Ky7m/MakingDotNETApplicationsFaster#4]
Hi, Igor, I added some runners to check the perfomance. Suddenly the build for Mono was broken. The build for windows looks good.

https://travis-ci.org/github/Ky7m/MakingDotNETApplicationsFaster/jobs/747784332

Attempting to gather dependency information for package 'Cake.0.19.5' with respect to project '/Users/travis/build/Ky7m/MakingDotNETApplicationsFaster/tools', targeting 'Any,Version=v0.0'
Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json.
  Method 'System.Net.Http.HttpClientHandler.get_ClientCertificates' not found.
An error occured while installing Cake.
The command "./build.sh" exited with 1.

**Comment by Ky7m** [comment]
fixed
